# pylint: skip-file
# Generated by Django 2.0.13 on 2019-05-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edid',
            name='file_base64',
            field=models.BinaryField(),
        ),
    ]
